version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
    ports:
      - "5001:5001"
    networks:
      - app-network
    command: uvicorn main:app --host 0.0.0.0 --port 5001 --reload

  db:
    image: timescale/timescaledb-ha:pg16
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/home/postgres/pgdata/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge